import numpy as np
import pandas as pd


# Splits ---------------------------------------------------------------------------------------------------
def build_random_kfold_splits(x, y, k = 5, seed = 42):
    """
    Builds random K-Fold splits from a set already separated into features and target.
    With k=5, it will create 5 splits where each split uses 20% of the data for validation
    and 80% for training.

    Arguments:
        x (pd.DataFrame): features
        y (pd.Series): target
        k (int): number of folds
        seed (int): random seed for reproducibility

    Returns:
        list[tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series]]: train-validation splits
    """
    np.random.seed(seed)

    # Shuffle indices and split into k folds
    indices = np.random.permutation(len(x))
    folds = np.array_split(indices, k)
    splits = []

    # Create train-validation splits for each fold
    for i in range(k):
        val_idx = folds[i]
        train_idx = np.concatenate([folds[j] for j in range(k) if j != i])

        x_fold = x.iloc[train_idx].copy()
        y_fold = y.iloc[train_idx].copy()

        xval_fold = x.iloc[val_idx].copy()
        yval_fold = y.iloc[val_idx].copy()

        splits.append((x_fold, y_fold, xval_fold, yval_fold))

    return splits


# Cross-Validation --------------------------------------------------------------------------------------
def cross_validate(x, y, eval_fn, strategy, xval = None, yval = None, group_col = "escuela",
                   k = 5, seed = 42, **kwargs):
    """
    Performs cross-validation using a specified strategy and evaluation function.
    
    This is a generic cross-validation wrapper that applies an evaluation function
    to each fold generated by the specified strategy.

    Arguments:
        x (pd.DataFrame): features
        y (pd.Series): target
        eval_fn (callable): evaluation function with signature eval_fn(x_fold, y_fold, xval_fold, yval_fold, **kwargs)
        strategy (str): cross-validation strategy {"random", "group", "temporal"}
        xval (pd.DataFrame): validation features for temporal strategy
        yval (pd.Series): validation target for temporal strategy
        group_col (str): grouping column for group-based validation
        k (int): number of folds for random K-Fold
        seed (int): random seed for reproducibility
        **kwargs: additional arguments passed to eval_fn

    Returns:
        list: results from eval_fn applied to each fold
    """ 
    splits = build_random_kfold_splits(x, y, strategy = strategy, xval = xval, yval = yval, group_col = group_col,
                             k = k, seed = seed)

    results = []

    for x_fold, y_fold, xval_fold, yval_fold in splits:
        result = eval_fn(x_fold, y_fold, xval_fold, yval_fold, **kwargs)
        results.append(result)
    return results


def cross_validate_model(dataset, binary_target = None, model_class = BinaryLogisticRegression, model_params = None, 
                         metric_fn = f1_score, **kwargs):
    """
    Performs cross-validation for a specified model across multiple folds.
    
    Arguments:
        dataset (pd.DataFrame): complete dev dataset containing features and target
        model_class: Model class to evaluate (default: BinaryLogisticRegression)
        model_params (dict): hyperparameters for the model (default: None)
        metric_fn (callable): metric function to evaluate (default: f1_score)
        **kwargs: additional arguments passed to cross_validate (strategy, k, seed, etc.)
    
    Returns:
        tuple: mean metric score, standard deviation of metric scores, number of splits [if results are scalar]
        dict: aggregated metrics across folds [if results are dictionaries]
    """
    dataset = _format_target_for_task(dataset, binary_target = binary_target)
    x, y = _split_features_and_target(dataset)

    if model_params is None:
        model_params = {}
    
    results = cross_validate(x, y, eval_fn = evaluate_fold_generic, model_class = model_class, model_params = model_params,
                             metric_fn = metric_fn, **kwargs)
    
    # Case 1: simple scalar metrics
    if isinstance(results[0], (int, float, np.floating)):
        return np.mean(results), np.std(results), len(results)

    # Case 2: dictionary of metrics (Binary)
    if binary_target is not None:
        return aggregate_binary_metrics(results)

    # Case 3: dictionary of metrics (Multiclass)
    return aggregate_dict_metrics(results)


# Grid Search --------------------------------------------------------------------------------------------
def build_param_combinations(param_grid):
    """
    Builds all hyperparameter combinations from a parameter grid.

    Arguments:
        param_grid (dict): dictionary where each key is a hyperparameter name and each value is a list of candidate values

    Returns:
        list[dict]: list of hyperparameter combinations
    """
    combinations = [{}]

    for param_name, param_values in param_grid.items():
        new_combinations = []

        for combination in combinations:
            for param_value in param_values:
                new_combination = combination.copy()
                new_combination[param_name] = param_value
                new_combinations.append(new_combination)

        combinations = new_combinations

    return combinations


def evaluate_param_grid(dataset, param_grid, binary_target = None, model_class = MLP,
                        base_model_params = None, metric_fn = evaluate_model, **kwargs):
    """
    Evaluates all hyperparameter combinations in a parameter grid using cross-validation.

    Arguments:
        dataset (pd.DataFrame): complete dev dataset containing features and target
        param_grid (dict): dictionary where each key is a hyperparameter name and each value is a list of candidate values
        binary_target (pd.Series or array-like): binary target values used to replace the original target (optional)
        model_class: model class to evaluate
        base_model_params (dict): fixed model hyperparameters included in every combination
        metric_fn (callable): metric function used for validation
        **kwargs: additional arguments passed to cross_validate_model
            (strategy, k, seed, xval, yval, etc.)

    Returns:
        pd.DataFrame: validation results for each hyperparameter combination
    """
    if base_model_params is None:
        base_model_params = {}

    combinations = build_param_combinations(param_grid)
    results = []

    for params in combinations:
        model_params = {**base_model_params, **params}

        results_cv = cross_validate_model(
            dataset,
            binary_target = binary_target,
            model_class = model_class,
            model_params = model_params,
            metric_fn = metric_fn,
            **kwargs
        )

        mean_metric, std_metric, n_splits = results_cv

        row = params.copy()
        row["mean_val_metric"] = mean_metric
        row["std_val_metric"] = std_metric
        row["n_splits"] = n_splits

        results.append(row)

    return pd.DataFrame(results)